version: '3.4'

services:
  callsheetapi:
    image: callsheetapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 4000:4000
