openapi: 3.0.3
info:
  title: Korfball CallSheet API
  description: Backend for the CallSheet viewer to show which callsheet item is currently active and which one is next.
  contact:
    email: mike@vanvendeloo.net
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: /api
 
tags:
  - name: callsheets
    description: callsheets
  - name: live
    description: Live callsheet
 
paths:
  /health:
    get:
      operationId: health
      responses:
         200:
          description: Success
          content:
            application/json:
              schema:
                type: string
